# Generated by Django 3.2.5 on 2021-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('voltage', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('power', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('date_stamp', models.DateField(auto_now_add=True)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
